<a href="https://colab.research.google.com/github/tilopez/GO_distance/blob/master/3_expectation_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Idea

In [0]:
import numpy as np

In [0]:
# matriz de distancias entre 5 genes
dist_nom = [['0', 'A', 'B', 'C', 'D'],['A', '0', 'E', 'F', 'G'],['B', 'E', '0', 'H', 'I'],['C', 'F', 'H', '0', 'J'],['D', 'G', 'I', 'J', '0']]
for i in dist_nom:
  print(i)

['0', 'A', 'B', 'C', 'D']
['A', '0', 'E', 'F', 'G']
['B', 'E', '0', 'H', 'I']
['C', 'F', 'H', '0', 'J']
['D', 'G', 'I', 'J', '0']


In [0]:
# matriz de resultados esperados
exp = [['AB', 'AC', 'AD', 'BC', 'BD', 'CD'],
        ['AE', 'AF', 'AG', 'EF', 'EG', 'FG'],
        ['BE', 'BH', 'BI', 'EH', 'EI', 'HI'],
        ['CF', 'CH', 'CJ', 'FH', 'FJ', 'HJ'],
        ['DG', 'DI', 'DJ', 'GI', 'GJ', 'IJ'],]
for i in exp:
  print(i)

['AB', 'AC', 'AD', 'BC', 'BD', 'CD']
['AE', 'AF', 'AG', 'EF', 'EG', 'FG']
['BE', 'BH', 'BI', 'EH', 'EI', 'HI']
['CF', 'CH', 'CJ', 'FH', 'FJ', 'HJ']
['DG', 'DI', 'DJ', 'GI', 'GJ', 'IJ']


In [0]:
# matriz de distancias de prueba
n = 5
dist = np.zeros((n,n))
for j in range(n):
  for i in range(j):
    dist[i,j] = i+j
dist = dist + dist.T
print(dist)

[[0. 1. 2. 3. 4.]
 [1. 0. 3. 4. 5.]
 [2. 3. 0. 5. 6.]
 [3. 4. 5. 0. 7.]
 [4. 5. 6. 7. 0.]]


In [0]:
# codificacion de la comparaciones
m = 0
for i in range(2,n):
  m = m + n - i

# 0 si A < B
# 1 si A = B
# 2 si A > B

# matriz de resultados esperados
exp = np.zeros((n,m))

exp[0,0] = 0
exp[0,1] = 0
exp[0,2] = 0
exp[0,3] = 1
exp[0,4] = 0
exp[0,5] = 0

exp[1,0] = 0
exp[1,1] = 0
exp[1,2] = 1
exp[1,3] = 1
exp[1,4] = 0
exp[1,5] = 0

exp[2,0] = 1
exp[2,1] = 1
exp[2,2] = 2
exp[2,3] = 2
exp[2,4] = 1
exp[2,5] = 1

exp[3,0] = 0
exp[3,1] = 0
exp[3,2] = 1
exp[3,3] = 1
exp[3,4] = 0
exp[3,5] = 0

exp[4,0] = 0
exp[4,1] = 0
exp[4,2] = 1
exp[4,3] = 0
exp[4,4] = 0
exp[4,5] = 0

print(exp)

[[0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [1. 1. 2. 2. 1. 1.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [0]:
# armar la matriz de las comparaciones entre distancias
m = 0
for i in range(2,n):
  m = m + n - i

rta = np.zeros((n,m))

for i in range(n):
  fila_dist = np.concatenate((dist[i,0:i],dist[i,i+1:n]))
  comps = np.zeros(m)
  cont = 0
  for j in range(n-2):
    for k in range(j+1,n-1):
      comps[cont] = 0 if fila_dist[j] < fila_dist[k] else 1 if fila_dist[j] == fila_dist[k] else 2
      cont = cont + 1
  rta[i,:] = comps

print(rta)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [0]:
eva = []

for i in range(n):
  word = []
  for j in range(m):
    if rta[i,j] == exp[i,j]:
      word.append("right")
    else:
      word.append("WRONG")
  eva.append(word)

print(rta,'\n')
print(exp,'\n')
for i in eva:
  print(i)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [1. 1. 2. 2. 1. 1.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]] 

['right', 'right', 'right', 'WRONG', 'right', 'right']
['right', 'right', 'WRONG', 'WRONG', 'right', 'right']
['WRONG', 'WRONG', 'WRONG', 'WRONG', 'WRONG', 'WRONG']
['right', 'right', 'WRONG', 'WRONG', 'right', 'right']
['right', 'right', 'WRONG', 'right', 'right', 'right']


# Función

In [0]:
def exp_matrix( dist, exp ):
  dist = dist.round(8)
  rta = np.zeros(exp.shape)
  [n,m] = exp.shape

  for i in range(n):
    fila_dist = np.concatenate((dist[i,0:i],dist[i,i+1:n]))
    comps = np.zeros(m)
    cont = 0
    for j in range(n-2):
      for k in range(j+1,n-1):
        comps[cont] = 0 if fila_dist[j] < fila_dist[k] else 1 if fila_dist[j] == fila_dist[k] else 2
        cont = cont + 1
    rta[i,:] = comps

  eva = []
  genes = []
  cant = 0

  for i in range(n):
    word = []
    for j in range(m):
      if rta[i,j] == exp[i,j]:
        word.append("right")
      else:      
        word.append("WRONG")
        cant += 1
        
        # determinar los genes que dieron el error
        cont = 0
        for k in range(n-1):
          for l in range(k,n):
            if k != i and l != i and k != l:
              if cont == j:
                genes.append([i+1, k+1, l+1])
              cont += 1

    eva.append(word)

  return(eva,cant,genes)

In [0]:
[exps,cant,genes]=exp_matrix(dist,exp)
print("Nro de errores: ", cant)
print(" ")
for i in exps:
  print(i)
print(" ")
for i in genes:
  print(i)

Nro de errores:  12
 
['right', 'right', 'right', 'WRONG', 'right', 'right']
['right', 'right', 'WRONG', 'WRONG', 'right', 'right']
['WRONG', 'WRONG', 'WRONG', 'WRONG', 'WRONG', 'WRONG']
['right', 'right', 'WRONG', 'WRONG', 'right', 'right']
['right', 'right', 'WRONG', 'right', 'right', 'right']
 
[1, 3, 4]
[2, 1, 5]
[2, 3, 4]
[3, 1, 2]
[3, 1, 4]
[3, 1, 5]
[3, 2, 4]
[3, 2, 5]
[3, 4, 5]
[4, 1, 5]
[4, 2, 3]
[5, 1, 4]
